AWSTemplateFormatVersion: 2010-09-09

Resources:

  InduceRuleTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        ZipFile: >
          import boto3

          import json

          import random

          import string

          import datetime

          import logging

          from botocore.exceptions import ClientError


          s3client = boto3.client('s3')

          logger = logging.getLogger()

          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              try:
                  startTime = datetime.datetime.utcnow()
                  logger.info(json.dumps(event))
                  region = context.invoked_function_arn.split(':')[3]

                  s3prefix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))
                  s3compBucket = s3prefix + "reinvent2017-config-ws-compbucket"
                  s3nonCompBucket = s3prefix + "reinvent2017-config-ws-noncompbucket"

                  s3client.create_bucket(Bucket=s3nonCompBucket, CreateBucketConfiguration={'LocationConstraint': region})
                  
                  s3client.create_bucket(Bucket=s3compBucket, CreateBucketConfiguration={'LocationConstraint': region})

                  s3client.put_bucket_versioning(Bucket=s3compBucket,VersioningConfiguration={'Status':'Enabled'})

                  s3client.put_bucket_lifecycle_configuration(Bucket=s3compBucket,LifecycleConfiguration={\
                      'Rules':[\
                          {\
                              'Prefix':'',\
                              'Status':'Enabled',\
                              'NoncurrentVersionTransitions':[\
                                  {\
                                  'NoncurrentDays':1,\
                                  'StorageClass':'GLACIER'\
                                  }\
                              ]\
                          }\
                      ]\
                  })

                  logger.info("Compliant S3 Bucket: " + s3compBucket + " Noncompliant S3 Bucket: " + s3nonCompBucket)

                  resource = {
                      'ResourceType': 'AWS::S3::Bucket',
                      'ResourceName': s3nonCompBucket,
                      'ValidationResources': {
                          'NON_COMPLIANT': s3nonCompBucket,
                          'COMPLIANT': s3compBucket
                      },
                      'StartTime': startTime.replace(microsecond=0).isoformat('T') + 'Z'
                  }

                  return resource

              except ClientError as e:
                  logger.error(e)



  CheckCloudTrailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        ZipFile: >
          import boto3

          import json

          import logging

          import datetime

          logger = logging.getLogger()

          logger.setLevel(logging.INFO)

          client = boto3.client("cloudtrail")

          config = boto3.client("config")

          def lambda_handler(event, context):

              logger.info(json.dumps(event));

              resource_name = event['Resource']['ResourceName']
              resource_type = event['Resource']['ResourceType']
              start_time = event['Resource']['StartTime']
              start_time_dt = datetime.datetime.strptime(start_time, "%Y-%m-%dT%H:%M:%SZ")
              logger.info('resource_name = ' + resource_name)
              logger.info('start_time = ' + start_time)
              logger.info('start_time_dt = ' + str(start_time_dt))

              #check presence in config first since it's faster than CloudTrailEvent
              not_compliant_s3_bucket_id = event['Resource']['ValidationResources']['NON_COMPLIANT']
              notcomp_config_response = config.get_compliance_details_by_resource(
                  ResourceType=resource_type,
                  ResourceId=resource_name
              )

              compliant_s3_bucket_id = event['Resource']['ValidationResources']['COMPLIANT']
              comp_config_response = config.get_compliance_details_by_resource(
                  ResourceType=resource_type,
                  ResourceId=resource_name
              )

              #both new SGs have been evaluated by config
              if notcomp_config_response['EvaluationResults'] and comp_config_response['EvaluationResults']:
                  return {
                      'Wait': 'false'
                  }


              response = client.lookup_events(
                  LookupAttributes=[
                      {
                          'AttributeKey': 'ResourceName',
                          'AttributeValue': resource_name
                      }
                  ],
                  StartTime=start_time_dt
              )
              logger.info(response)

              if not response['Events']:
                  return {
                      'Wait': 'true'
                  }

              return {
                  'Wait': 'false',
                  'CloudTrailEvent': response['Events'][0]['CloudTrailEvent']
              }


  CheckComplianceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        ZipFile: >
          import boto3

          import botocore

          import json

          import logging

          logger = logging.getLogger()

          logger.setLevel(logging.INFO)

          client = boto3.client("config");

          def lambda_handler(event, context):

              resources = event['Resource']['ValidationResources']
              resource_type = event['Resource']['ResourceType']
              logger.info('resource_type = ' + resource_type)
              update_points = "Yes"

              not_compliant_s3_bucket_id = resources['NON_COMPLIANT']
              compliant_s3_bucket_id = resources['COMPLIANT']

              #check not compliant for success first
              resource_name = not_compliant_s3_bucket_id
              response = client.describe_compliance_by_resource(
                  ResourceType=resource_type,
                  ResourceId=resource_name
                  )
              logger.info(json.dumps(response));

              if len(response['ComplianceByResources']) == 0:
                  return {
                      'Status': 'ERROR',
                      'Response': json.dumps(response)
                      }

              compliance = response['ComplianceByResources'][0]['Compliance']['ComplianceType']
              if compliance != "NON_COMPLIANT":
                  logger.info(compliance + " NON_COMPLIANT")
                  update_points = "No"

              #check compliant SG next to make sure marked compliant
              resource_name = compliant_s3_bucket_id
              response = client.describe_compliance_by_resource(
                  ResourceType=resource_type,
                  ResourceId=resource_name
                  )
              logger.info(json.dumps(response));

              if len(response['ComplianceByResources']) == 0:
                  return {
                      'Status': 'ERROR',
                      'Response': json.dumps(response)
                      }

              compliance = response['ComplianceByResources'][0]['Compliance']['ComplianceType']
              if compliance != "COMPLIANT":
                  logger.info(compliance + " COMPLIANT")
                  update_points="No"

              return {
                  'UpdatePoints': update_points
              }


  UpdateScoreFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        ZipFile: >
          import json

          import logging

          import urllib

          logger = logging.getLogger()

          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):

              logger.info(json.dumps(event));

              jwt = event['Jwt']
              leaderboard_url = event['Leaderboard']['Url']
              rule_id = event['Leaderboard']['RuleId']
              points = event['Leaderboard']['Points']
              logger.info('jwt = ' + jwt)
              logger.info('leaderboard_url = ' + leaderboard_url)
              logger.info('rule_id = ' + rule_id)
              logger.info('points = ' + points)

              payload = {
                  'ruleId': rule_id,
                  'points': points
              }

              req = urllib.request.Request(leaderboard_url)
              req.add_header('Authorization', jwt)

              response = urllib.request.urlopen(req, data=bytes(json.dumps(payload), encoding='utf-8'))
              responseBody = json.loads(response.read().decode('utf-8'))

              logger.info('response = ' + json.dumps(responseBody));

              return {
                  'StatusCode': response.status
              }



  CleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.6
      Timeout: 10
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        ZipFile: >
          import boto3

          import json

          import string

          import logging

          from botocore.exceptions import ClientError


          s3client = boto3.client('s3')

          logger = logging.getLogger()

          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):

              logger.info(json.dumps(event))
              s3nonCompBucket = event['Resource']['ValidationResources']['NON_COMPLIANT']
              s3compBucket = event['Resource']['ValidationResources']['COMPLIANT']

              try:

                  response = s3client.delete_bucket(
                      Bucket=s3nonCompBucket
                  )
                  logger.info("Delete first S3 Bucket: " + json.dumps(response))

                  response = s3client.delete_bucket(
                      Bucket=s3compBucket
                  )
                  logger.info("Delete second S3 Bucket: " + json.dumps(response))

                  return {
                      'Cleanup-Status': 'S3 Buckets successfully deleted.'
                  }

              except ClientError as e:
                  print(e)


  LambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies: 
        - PolicyName: LambdaConifigCheckPolicy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
               - Effect: Allow
                 Resource: '*'
                 Action:
                  - s3:CreateBucket
                  - s3:ListBucket
                  - s3:DeleteBucket
                  - s3:PutBucketVersioning
                  - s3:PutLifecycleConfiguration
                  - config:DescribeComplianceByResource
                  - config:GetComplianceDetailsByResource
                  - cloudtrail:LookupEvents


  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: "ConfigRulesWorkshop-2-S3-Version-Lifecycle-Rule"
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A test harness for S3 Versioning and Lifecycle Policy Rule",
              "StartAt": "setup",
              "States": {
                "setup": {
                  "Type": "Pass",
                  "Result": {
                    "Url": "https://f0ah4xd3c0.execute-api.ap-northeast-1.amazonaws.com/prod/teamscores",
                    "RuleId": "S3_Version_Lifecycle",
                    "Points": "100"
                  },
                  "ResultPath": "$.Leaderboard",
                  "Next": "induce_rule"
                },
                "induce_rule": {
                  "Type": "Task",
                  "Resource": "${InduceRuleTriggerFunctionArn}",
                  "ResultPath": "$.Resource",
                  "Next": "wait_ten_seconds"
                },
                "wait_ten_seconds" : {
                  "Type" : "Wait",
                  "Seconds" : 10,
                  "Next": "check_cloudtrail"
                },
                "check_cloudtrail" : {
                  "Type" : "Task",
                  "Resource": "${CheckCloudTrailFunctionArn}",
                  "ResultPath": "$.CloudTrail",
                  "Next": "wait_longer"
                },
                "wait_longer": {
                  "Type" : "Choice",
                  "Choices": [
                    {
                      "Variable": "$.CloudTrail.Wait",
                      "StringEquals": "true",
                      "Next": "wait_ten_seconds"
                    },
                    {
                      "Variable": "$.CloudTrail.Wait",
                      "StringEquals": "false",
                      "Next": "wait_three_seconds"
                    }
                  ],
                  "Default": "unknown_wait"
                },
                "unknown_wait": {
                  "Type": "Fail",
                  "Error": "non-boolean value for wait_longer wait value: $.CloudTrail.Wait"
                },
                "wait_three_seconds" : {
                  "Type" : "Wait",
                  "Seconds" : 3,
                  "Next": "check_compliance"
                },
                "check_compliance": {
                  "Type" : "Task",
                  "Resource": "${CheckComplianceFunctionArn}",
                  "ResultPath": "$.UpdatePoints",
                  "Next": "cleanup"
                },
                "cleanup": {
                  "Type": "Task",
                  "Resource": "${CleanupFunctionArn}",
                  "ResultPath": "$.CleanupStatus",
                  "Next": "is_compliant"
                },
                "is_compliant": {
                  "Type" : "Choice",
                  "Choices": [
                    {
                      "Variable": "$.UpdatePoints.UpdatePoints",
                      "StringEquals": "Yes",
                      "Next": "update_score"
                    },
                    {
                      "Variable": "$.UpdatePoints",
                      "StringEquals": "No",
                      "Next": "skip_update_score"
                    }
                  ],
                  "Default": "skip_update_score"
                },
              	"skip_update_score": {
                  "Type": "Fail",
                  "Error": "Your rule did not mark each S3 bucket appropriately."
                },
                "update_score": {
                  "Type": "Task",
                  "Resource": "${UpdateScoreFunctionArn}",
                  "ResultPath": "$.Result",
                  "End": true
                }
              }
            }
          - {
              InduceRuleTriggerFunctionArn: !GetAtt [ InduceRuleTriggerFunction, Arn ],
              CheckCloudTrailFunctionArn: !GetAtt [ CheckCloudTrailFunction, Arn ],
              CheckComplianceFunctionArn: !GetAtt [ CheckComplianceFunction, Arn ],
              UpdateScoreFunctionArn: !GetAtt [ UpdateScoreFunction, Arn ],
              CleanupFunctionArn: !GetAtt [ CleanupFunction, Arn ]
            }
      RoleArn: !GetAtt StatesExecutionRole.Arn
